name: build-and-deploy
on:
  push:
    branches: [ "main" ]  # змінюй під свою гілку

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          VITE_MODEL_API: ${{ secrets.VITE_MODEL_API }}
          VITE_MODEL_API_TOKEN: ${{ secrets.VITE_MODEL_API_TOKEN }}
          VITE_ADMIN_USERNAME: ${{ secrets.VITE_ADMIN_USERNAME }}
          VITE_ADMIN_PASSWORD: ${{ secrets.VITE_ADMIN_PASSWORD }}

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          if [ -n "${{ secrets.KNOWN_HOSTS }}" ]; then
            echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          else
            ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts 2>/dev/null
          fi

      - name: Push dist/ to server
        run: |
          rsync -az --delete -e "ssh -p ${{ secrets.SSH_PORT }}" \
            dist/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/"

      - name: Install PM2 and serve app
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "cd ${{ secrets.DEPLOY_PATH }} && \
             npm install -g pm2 serve 2>/dev/null || true && \
             pm2 delete ms-admin 2>/dev/null || true && \
             pm2 serve . 9200 --name ms-admin --spa && \
             pm2 startup systemd -u $USER --hp $HOME 2>/dev/null || true && \
             pm2 save"
